# Generated by Django 5.1.6 on 2025-03-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='scan',
            name='document_content',
            field=models.TextField(default=''),
        ),
    ]
